### ISSUE TITLE
How is doc_ids supposed to work?

### ISSUE THREAD

**Issue by jrounds** [ropensci/elastic#90] opened 2015-10-07 22:46 UTC
I am hoping to use bulk with a data.frame but I need control over the ID.  I am about to write my own, but I am curious how this is imagined to work.  For example
```
elastic:::docs_bulk.data.frame(iris, index="iris_data", type="flower_record",
                               doc_ids= paste0("custom_id_",1:nrow(iris)))
```

I would expect to see the custom id on the elasticsearch head but I see 0:149.

**Comment by jrounds** [comment] 2015-10-07 22:55
BTW I wrote this before I saw that docs_bulk had a df version, I get the expected thing this way, but I would like to standardize around the package if possible.

```

docs_bulk.data.frame2 = function(df, index, type, id, just.ret=FALSE){
  json.df = toJSON(df)
  json.df = gsub("[","", json.df, fixed=TRUE)
  json.df = gsub("]", "", json.df, fixed=TRUE)
  json.df = gsub("},{", "}@@@JSON_SPLIT_RECORD@@@JeremiahRounds{",json.df, fixed=TRUE)
  json.df = unlist(strsplit(json.df,"@@@JSON_SPLIT_RECORD@@@JeremiahRounds", fixed=TRUE ))
  index_line_close = '"}}'
  index_line = '{"index":{"_index":"@@@INDEX@@@","_type":"@@@TYPE@@@","_id":"'
  index_line = gsub("@@@INDEX@@@", index, index_line)
  index_line = gsub("@@@TYPE@@@", type, index_line)
  index_lines = paste0(index_line, id, index_line_close)
  args = vector("list", length = length(index_lines)*2)
  int =1:length(index_lines)
  for(i in int){
    j = 2*i - 1
    args[[j]] = index_lines[[i]]
    args[[j+1]] = json.df[i]
  }
  op = function(...) paste(..., sep="\n", collapse= "\n")
  bulk = do.call(op,args)
  tmp = tempfile()
  cat(bulk, file=tmp)
  cat("\n", file=tmp, append=TRUE)
  ret = docs_bulk(tmp)
  file.remove(tmp)
  return(ret)
}
docs_bulk.data.frame2(iris, index="iris_data", type="flower_record", id = paste0("custom_id_",1:nrow(iris)))
```

**Comment by sckott** [comment] 2015-10-07 23:21
thanks for your message. 

I think the problem is here https://github.com/ropensci/elastic/blob/master/R/docs_bulk.r#L216 in which I need to allow user input document IDs to go through directly instead of doing `-1` on, which is used to achieve the 0 based indexing Elasticsearch uses on documents.

**Comment by sckott** [comment] 2015-10-07 23:42
I think last commit e55ba37 addresses your first comment, reinstall and that should fix it.

**Comment by sckott** [comment] 2015-10-07 23:43
Let me know if there's anything else in that fxn above you wrote that you want in the pkg

**Comment by sckott** [comment] 2015-10-29 23:28
@jrounds any further thoughts?  closing if not

**Closed** 2016-01-05 20:15 UTC
