### ISSUE TITLE
Prevent 404 Exception

### ISSUE THREAD

**Issue by jaredlander** [ropensci/elastic#131] opened 2016-05-06 22:52 UTC
Is there a way to pass an argument to scroll that allows a 404 error to be returned as a valid response?  Something a long the lines of https://github.com/elastic/elasticsearch-net/issues/1518, specifically this part `RequestConfiguration(r => r.AllowedStatusCodes(404))`.

Perhaps it can be added to the `args` in the call to `scroll_POST`?

**Comment by sckott** [comment] 2016-05-06 23:05
Interesting. I'll look into it. 

So I understand the use case, is this correct? -> When scrolling, the last request can 404 - in which case you don't want the client to stop with error, but proceed as if the response was 200

**Comment by jaredlander** [comment] 2016-05-08 19:58
Well, I want it not to error out.  I want the last request to to be normal, maybe with some indication that it is done.  I'm running scroll, probably not in the best way (https://github.com/jaredlander/TextInfo/blob/master/R/PairExtraction.r#L264) and when it hits that 404 the whole thing falls apart.

**Comment by sckott** [comment] 2016-05-09 22:46
Okay. I'll report back soon

**Comment by jaredlander** [comment] 2016-05-09 23:19
I got something working in the link below. Not sure it's great but it's working for now.  Maybe the end of the scroll is marked differently so we can have the `while` conditioned on it not being the end?  But then that would be adding stuff onto the elastic response and seems inelegant.  So maybe this can be built into `elasticdsl`?

https://github.com/jaredlander/TextInfo/blob/master/R/PairExtraction.r#L267

**Comment by sckott** [comment] 2016-05-10 19:13
> So maybe this can be built into `elasticdsl`

Perhaps, though I think it makes more sense here.

I like the idea of the allowed http status responses - I'll try that soon and push something up to try out

**Comment by sckott** [comment] 2016-05-10 20:46
After looking at your code and running through different scenarios, I still can't reproduce any 404s using `scroll()` - Can you share what situations causes 404s?  On a last call I don't get an error back but a 200 response, and just no results in `hits`

**Comment by jaredlander** [comment] 2016-05-10 21:16
When calling to an instance on a remote server I get the 404 error 70% of the time, though it might not necessarily always be on the last response.  Unfortunately, I can't share the database I'm using but will see if I can setup an example database.

**Comment by sckott** [comment] 2016-05-10 21:55
Thanks. Can you tell me what version of Elasticsearch is running on the remote, and what version of `elastic` you're using

**Comment by sckott** [comment] 2019-04-05 23:02
closing - if anyone else wants this chime in and can reconsider

**Closed by sckott** 2019-04-05 23:02 UTC
