### ISSUE TITLE
JSON Data type of property can not be fetched/queried?

### ISSUE THREAD

**Issue by bajorge** [ropensci/elastic#41] opened 2015-02-12 04:39 UTC
Hi ROpensci, 

Just wondering why I can't get the type of my fields? I am expecting the result would be numeric, ie. integer or float. 

Using the mapping command as below. 

$out <- index_get(index='gasen')
$names(out$gasen$mappings$com$properties$SCORE)
[1] "type"

When executing to get the data type, the result becomes NULL.

$names(out$gasen$mappings$com$properties$SCORE$type)
NULL

Refer to source JSON below. 

Is this the default/normal/correct behavior? 
Any advise/work-around please. 

Sincerely, 

Jaime Jr

Source JSON:    http://localhost:9200/_plugin/head/:

    "state": "open",
    "settings": {
        "index": {
            "number_of_replicas": "1",
            "number_of_shards": "2",
            "uuid": "65tNPda7Qe--4qdMjAq74w",
            "version": {
                "created": "1030199"
            }
        }
    },

"mappings": {

       "com": {
        "properties": {
            "CHANNEL": {
                "type": "string"
            },
            "SCORE": {
                "type": "float"
            },
            "CONTENT": {
                "type": "string"
            },
            "CREATE ON": {
                "format": "dateOptionalTime",
                "type": "date"
            },
            "ID": {
                "type": "string"
            },
            "SENTIMENT": {
                "type": "string"
            },
            "CREATE BY": {
                "type": "string"
            }
        }
    }
},

**Comment by sckott** [comment] 2015-02-12 07:02
hi @bajorge - Hmm, it's not common to assign things to variable names with `$` preceding the var name. 

I think the problem is though that you are calling the function `names()` on `out$gasen$mappings$com$properties$SCORE$type`, which could be `NULL`, 

Instead, just execute `out$gasen$mappings$com$properties$SCORE$type` to get the value for the type, e.g,. could be `string`, `date`, etc. 

does that work?

**Comment by bajorge** [comment] 2015-02-12 07:43
hi @sckott, 

Thanks for the quick response!  Run and output is NULL. It does not works. 

> out$gasen$mappings$com$properties$SCORE$type
NULL

I also notice this to other indexes, our example ie, shakespeare and the result is the same. Believe this is how it normally behaves. Seems this is a bug. 

> names(out$shakespeare$mappings$line$properties$line_id$type)
NULL

Also from the start, complete trace, base from the documentation.

> out <- index_get(index='shakespeare')
> names(out$shakespeare$mappings)
[1] "line"  "scene" "act"  
> names(out$shakespeare$mappings$line)
[1] "properties"
> names(out$shakespeare$mappings$line$properties)
[1] "line_id"       "line_number"   "play_name"     "speaker"      
[5] "speech_number" "text_entry"   
> names(out$shakespeare$mappings$line$properties$line_id)
[1] "type"
> names(out$shakespeare$mappings$line$properties$line_id$type)
NULL 

Appreciate the help!!!

**Comment by sckott** [comment] 2015-02-12 15:55
yes, I get all the same as you, but this part: `names(out$shakespeare$mappings$line$properties$line_id$type)` is where you don't want to use `names()`, just index to the value, where hopefully you also get this:

```f
out$shakespeare$mappings$line$properties$line_id$type
[1] "long"
```

**Comment by sckott** [comment] 2015-02-18 19:03
closing due to inactvity

**Closed by sckott** 2015-02-18 19:03 UTC
